version: '3.8'
services:
  database:
    image: mariadb:latest
    container_name: new_mdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin_password
      MYSQL_DATABASE: QLKH
      MYSQL_USER: admin
      MYSQL_PASSWORD: Password123!
    volumes:
      - db_data:/var/lib/mysql            # Lưu dữ liệu database
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Khởi tạo cơ sở dữ liệu ban đầu
    ports:
      - "3306:3306"
    networks:
      - qlkh-network

  backend:
    build:
      context: ./backend                  # Trỏ tới thư mục backend
      dockerfile: Dockerfile              # Tên file Dockerfile
    container_name: vts-backend
    restart: always
    depends_on:
      - database                          # Đảm bảo database khởi động trước
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/QLKH
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: Password123!
    ports:
      - "8080:8080"
    networks:
      - qlkh-network

  frontend:
    build:
      context: ./frontend                 # Trỏ tới thư mục frontend
      dockerfile: Dockerfile              # Tên file Dockerfile
    container_name: vts-frontend
    restart: always
    depends_on:
      - backend                           # Đảm bảo backend khởi động trước
    environment:
      VITE_API_URL: http://localhost:8080/api
    ports:
      - "3000:80" # Kết nối cổng 80 trong container (Nginx) sang cổng 3000 trên host
    networks:
      - qlkh-network

volumes:
  db_data:                                # Volume lưu trữ dữ liệu database

networks:
  qlkh-network:
    driver: bridge
